name: Build & Publish

on:
  push:
    tags:
      - v*

jobs:
  gri:
    name: Get Docker repo ID
    runs-on: ubuntu-latest
    outputs:
      repo-id: ${{ steps.get-repo-id.outputs.repo-id }}
    steps:
      - id: get-repo-id
        run: |
          REPO_ID=$(echo ${{ github.repository }} | cut -d'/' -f2)
          echo "repo-id=$REPO_ID" >> $GITHUB_OUTPUT
  run-publish-workflow:
    name: Run `publish` workflow
    needs: gri
    uses: ./.github/workflows/libpublish.yml
    permissions:
      packages: write
    with:
      image-namespace: ${{ github.repository_owner }}
      image-repo: ${{ needs.gri.outputs.repo-id }}
      labels: org.opencontainers.image.authors=AN Author <author@example.org>
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
