name: Build & Test

on:
  pull_request:
  push:
    branches:
      - '**'
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}

jobs:
  pre-commit:
    name: Run `pre-commit`
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.0
  gri:
    name: Get Docker repo ID
    runs-on: ubuntu-latest
    outputs:
      repo-id: ${{ steps.get-repo-id.outputs.repo-id }}
    steps:
      - id: get-repo-id
        run: |
          REPO_ID=$(echo ${{ github.repository }} | cut -d'/' -f2)
          echo "repo-id=$REPO_ID" >> $GITHUB_OUTPUT
  run-test-workflow:
    name: Run `test` workflow
    needs:
      - gri
      - pre-commit
    uses: ./.github/workflows/libtest.yml
    permissions:
      contents: write
    with:
      image-namespace: dafyddj
      image-repo: base-docker-build
    secrets:
      push-token: ${{ secrets.PUSH_TOKEN }}
